### ISSUE TITLE
Adapter crashes after few minutes

### ISSUE THREAD

**Issue by dskvml** [intellicasa/ioBroker.blauberg-ventilation#5]
<html>
<body>

host.raspberrypi | 2023-10-21 16:46:47.825 | warn | Do not restart adapter system.adapter.blauberg-ventilation.0 because restart loop detected
-- | -- | -- | --
host.raspberrypi | 2023-10-21 16:46:47.824 | error | instance system.adapter.blauberg-ventilation.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
blauberg-ventilation.0 | 2023-10-21 16:46:47.187 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
blauberg-ventilation.0 | 2023-10-21 16:46:47.181 | error | Cannot read properties of null (reading 'ipAddress')
blauberg-ventilation.0 | 2023-10-21 16:46:47.180 | error | TypeError: Cannot read properties of null (reading 'ipAddress') at /opt/iobroker/node_modules/iobroker.blauberg-ventilation/main.js:266:36 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async asyncForEach (/opt/iobroker/node_modules/iobroker.blauberg-ventilation/main.js:15:3)
blauberg-ventilation.0 | 2023-10-21 16:46:47.179 | error | unhandled promise rejection: Cannot read properties of null (reading 'ipAddress')
blauberg-ventilation.0 | 2023-10-21 16:46:47.178 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

**Comment by intellicasa** [comment]
I'm already aware of it. I'll fix it in the next couple of days

**Comment by intellicasa** [comment]
I wanted to take a further look on today, but unfortunately I'm facing some issues with my dev environment. I'm working with Visual Studio and I have a dev-server running remote on a virtual server. For some reason it asks for port 20426 at startup which isn't available and the app crashes therefore. I try to find the problem

**Comment by intellicasa** [comment]
Seems to work for the moment. The problem was with rejected promises. Works in my dev environment. Feel free to test it.
